src/Entity/Quizz/UserQuestionResult.php
<?php

namespace App\Entity\Quizz;

use App\Repository\Quizz\UserQuestionResultRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserQuestionResultRepository::class)
 */
class UserQuestionResult
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=UserQuestion::class, inversedBy="result", cascade={"persist", "remove"})
     */
    private $userQuestion;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isValid;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserQuestion(): ?UserQuestion
    {
        return $this->userQuestion;
    }

    public function setUserQuestion(?UserQuestion $userQuestion): self
    {
        $this->userQuestion = $userQuestion;

        $userQuestion->setResult($this);

        return $this;
    }

    public function isValid(): ?bool
    {
        return $this->isValid;
    }

    public function setIsValid(bool $isValid): self
    {
        $this->isValid = $isValid;

        return $this;
    }
}

src/Entity/Quizz/UserQuizz.php
<?php

namespace App\Entity\Quizz;

use App\Entity\User;
use App\Repository\Quizz\UserQuizzRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserQuizzRepository::class)
 */
class UserQuizz
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="quizzs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Quizz::class)
     */
    private $quizz;

    /**
     * @ORM\OneToMany(targetEntity=UserQuestion::class, mappedBy="userQuizz", orphanRemoval=true, cascade={"persist"})
     */
    private $userQuestions;

    /**
     * @ORM\Column(type="integer")
     */
    private $currentQuestion;

    /**
     * @ORM\OneToOne(targetEntity=UserQuizzResult::class, cascade={"persist", "remove"})
     */
    private $result;

    public function __construct()
    {
        $this->userQuestions = new ArrayCollection();
        $this->currentQuestion = 1;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?UserInterface
    {
        return $this->user;
    }

    public function setUser(?UserInterface $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getQuizz(): ?Quizz
    {
        return $this->quizz;
    }

    public function setQuizz(?Quizz $quizz): self
    {
        $this->quizz = $quizz;

        return $this;
    }

    /**
     * @return Collection|UserQuestion[]
     */
    public function getUserQuestions(): Collection
    {
        return $this->userQuestions;
    }

    public function addUserQuestion(UserQuestion $userQuestion): self
    {
        if (!$this->userQuestions->contains($userQuestion)) {
            $this->userQuestions[] = $userQuestion;
            $userQuestion->setUserQuizz($this);
        }

        return $this;
    }

    public function removeUserQuestion(UserQuestion $userQuestion): self
    {
        if ($this->userQuestions->removeElement($userQuestion)) {
            // set the owning side to null (unless already changed)
            if ($userQuestion->getUserQuizz() === $this) {
                $userQuestion->setUserQuizz(null);
            }
        }

        return $this;
    }

    public function getCurrentQuestion(): ?int
    {
        return $this->currentQuestion;
    }

    public function setCurrentQuestion(int $currentQuestion): self
    {
        $this->currentQuestion = $currentQuestion;

        return $this;
    }

    public function getResult(): ?UserQuizzResult
    {
        return $this->result;
    }

    public function setResult(?UserQuizzResult $result): self
    {
        $this->result = $result;

        return $this;
    }
}

src/Form/UserQuizzType.php
<?php

namespace App\Form;

use App\Entity\Quizz\UserQuizz;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserQuizzType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('currentQuestion', HiddenType::class)
            ->add('userQuestions', CollectionType::class, [
                'entry_type' => UserQuestionType::class,
                'entry_options' => [
                    'view' => $options['view'],
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => UserQuizz::class,
            'view' => false,
        ]);
    }

    public function getBlockPrefix()
    {
        return "user_quizz";
    }
}

src/Controller/Quizz/UserQuizzController.php
<?php

namespace App\Controller\Quizz;

use App\Entity\Quizz\Domain;
use App\Entity\Quizz\UserQuizz;
use App\Form\UserQuizzType;
use App\Service\UserQuizzGeneratorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserQuizzController extends AbstractController
{
    public function __construct(
        private UserQuizzGeneratorInterface $userQuizzGenerator,
    )
    {
    }

    #[Route('/user-quizz/{id}', name: 'userquizz_index', requirements: ['id' => '\d+'])]
    public function index(Request $request, UserQuizz $userQuizz): Response
    {
        $form = $this->createForm(UserQuizzType::class, $userQuizz);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->getDoctrine()->getManager()->persist($userQuizz);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('userquizz_result_compute', [
                'id' => $userQuizz->getId(),
            ]);
        }

        return $this->render('userquizz/index.html.twig', [
            'userQuizz' => $userQuizz,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/user-quizz/domain/{id}/generate', name: 'userquizz_generate_by_domain', requirements: ['id' => '\d+'])]
    public function generateByDomain(Domain $domain): Response
    {
        $userQuizz = ($this->userQuizzGenerator->generateByDomain($domain))
            ->setUser($this->getUser());

        $this->getDoctrine()->getManager()->persist($userQuizz);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('userquizz_index', [
            'id' => $userQuizz->getId()
        ]);
    }

    #[Route('/user-quizz/{id}/update', name: 'userquizz_update', methods: ['POST'], requirements: ['id' => '\d+'])]
    public function update(Request $request, UserQuizz $userQuizz): Response
    {
        $form = $this->createForm(UserQuizzType::class, $userQuizz);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->persist($userQuizz);
            $this->getDoctrine()->getManager()->flush();

            return $this->json([
                'success' => true
            ]);
        }

        return $this->json([
            'success' => false
        ]);
    }
}

src/Controller/UserQuizzController.php
<?php

namespace App\Controller;

use App\Repository\Quizz\DomainRepository;
use App\Repository\Quizz\UserQuizzRepository;
use App\Service\UserQuizzGeneratorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserQuizzController extends AbstractController
{
    public function __construct(
        private UserQuizzGeneratorInterface $userQuizzGenerator,
        private DomainRepository $domainRepository,
        private UserQuizzRepository $userQuizzRepository,
    )
    {
    }

    #[Route('/user-quizz/{id}', name: 'userquizz_index')]
    public function index(int $id): Response
    {
        $userQuizz = $this->userQuizzRepository->find($id);

        return $this->render('userquizz/index.html.twig', [
            'userQuizz' => $userQuizz,
        ]);
    }

    #[Route('/user-quizz/domain/{id}/generate', name: 'userquizz_generate_by_domain')]
    public function generateByDomain(int $id): Response
    {
        $domain = $this->domainRepository->find($id);

        $userQuizz = ($this->userQuizzGenerator->generateByDomain($domain))
            ->setUser($this->getUser());

        $this->getDoctrine()->getManager()->persist($userQuizz);
        $this->getDoctrine()->getManager()->flush();

        return $this->redirectToRoute('userquizz_index', [
            'id' => $userQuizz->getId()
        ]);
    }
}

templates/userquizz/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DashboardController!{% endblock %}

{% block body %}
    <div class="container">
        <div class="card mt-0" data-controller="userquizz" data-userquizz-userquizz-value="{{ userQuizz.id }}">
            {{ form_start(form, { attr: {'data-userquizz-target': 'form'} }) }}

            <div class="card-body">
                {{ form_errors(form) }}

                {% for userQuestionField in form.userQuestions %}
                    <div class="question" data-userquizz-target="question">
                        <div class="card-title">
                            {{ userQuestionField.vars.question.value }}
                        </div>
                        <div class="card-text">
                            {{ form_row(userQuestionField.answers) }}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="card-links">
                <button type="button" class="btn btn-secondary mr-2" data-action="userquizz#previous">
                    Previous
                </button>
                <button type="button" class="btn btn-secondary mr-2" data-action="userquizz#next">
                    Next
                </button>
                <button type="submit" class="btn btn-primary">
                    Finish
                </button>
            </div>

            {{ form_widget(form.currentQuestion, { attr: {'data-userquizz-target': 'current'} }) }}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/userquizz/result.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DashboardController!{% endblock %}

{% block body %}
    <div class="container">
        <div class="card mt-0">
            <div class="card-body">
                <div class="card-text">
                    <div class="text-center mb-5">
                        <div class="text-center text-8xl {{ userQuizz.result.success ? 'text-success' : 'text-error' }}">
                            <i class="fas {{ userQuizz.result.success ? 'fa-thumbs-up' : 'fa-thumbs-down' }}"></i>
                        </div>

                        <div class="text-4xl">
                            {{ (userQuizz.result.success ? 'quizz.result.success.title' : 'quizz.result.error.title') | trans }}
                        </div>

                        <div class="text-xl">
                            {{ (userQuizz.result.success ? 'quizz.result.success.message' : 'quizz.result.error.message') | trans }}
                        </div>
                    </div>

                    <div>

                        {% for userQuestionField in form.userQuestions %}
{#                            <div class="question" data-userquizz-target="question">#}
{#                                <div class="card-title">#}
{#                                    {{ userQuestionField.vars.question.value }}#}
{#                                </div>#}
{#                                <div class="card-text">#}
{#                                    {{ form_row(userQuestionField.answers) }}#}
{#                                </div>#}
{#                            </div>#}

                        <div class="question-result {{ userQuestionField.vars.value.result.valid ? 'success' : 'error' }}">
                            <div class="title">{{ (userQuestionField.vars.value.result.valid ? 'Correct' : 'Incorrect') | trans }}</div>
                            <div class="question">{{ userQuestionField.vars.question.value }}</div>
                            {{ form_row(userQuestionField.answers) }}
                        </div>
                        {% endfor %}
                    </div>

                </div>
            </div>

            <div class="card-link text-center">
                <a href="{{ path('dashboard') }}" class="btn btn-primary">
                    Revenir au tableau de bord
                </a>
            </div>
        </div>
    </div>
{% endblock %}